### ISSUE TITLE
Exception in TapPatternDetectorService when starting app

### ISSUE THREAD

**Issue by vsaw** [psycholold/TapToUnlock#21]
```
01-25 10:44:48.714    7990-7990/com.abominableshrine.taptounlock E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.abominableshrine.taptounlock, PID: 7990
    java.lang.IllegalArgumentException: fromTime: 8178544177 toTime: -150000000
            at com.abominableshrine.taptounlock.TapPatternDetectorClient.requestRecentTaps(TapPatternDetectorClient.java:81)
            at com.abominableshrine.taptounlock.RecordPatternActivity$RPAOnClickListener.onClick(RecordPatternActivity.java:129)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19749)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by hbibel** [comment]
Which branch is that?

**Comment by vsaw** [comment]
Should be in develop by now.

Everything still works, that's why I haven't looked into it yet
