### ISSUE TITLE
Pressing "Back" after Recording of pattern throws Exception

### ISSUE THREAD

**Issue by vsaw** [psycholold/TapToUnlock#34]
```
01-26 21:04:43.193  17511-17511/com.abominableshrine.taptounlock E/ActivityThread﹕ Activity com.abominableshrine.taptounlock.RecordPatternActivity has leaked ServiceConnection com.abominableshrine.taptounlock.RecordPatternActivity$1@1dc432f5 that was originally bound here
    android.app.ServiceConnectionLeaked: Activity com.abominableshrine.taptounlock.RecordPatternActivity has leaked ServiceConnection com.abominableshrine.taptounlock.RecordPatternActivity$1@1dc432f5 that was originally bound here
            at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1072)
            at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:966)
            at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1768)
            at android.app.ContextImpl.bindService(ContextImpl.java:1751)
            at android.content.ContextWrapper.bindService(ContextWrapper.java:538)
            at com.abominableshrine.taptounlock.RecordPatternActivity.onCreate(RecordPatternActivity.java:81)
            at android.app.Activity.performCreate(Activity.java:5933)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by vsaw** [comment]
@psycholold please assign to the "Must Do" milestone if important for Wednesday!

**Comment by hbibel** [comment]
I noticed this exception as well. This is not a "must do", but I'll take a look at it. I think I know where the mistake is.

**Comment by vsaw** [comment]
If the rest works we don't need to fix it :)
